# Generated by Django 5.2.5 on 2025-08-28 01:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0002_departamento_deleted_at_puesto_deleted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalHorario",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("nombre", models.CharField(db_index=True, max_length=120)),
                (
                    "clave",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical horario",
                "verbose_name_plural": "historical horarios",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTurno",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("nombre", models.CharField(db_index=True, max_length=120)),
                (
                    "clave",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical turno",
                "verbose_name_plural": "historical turnos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("nombre", models.CharField(max_length=120, unique=True)),
                (
                    "clave",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cat_horarios",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Turno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("nombre", models.CharField(max_length=120, unique=True)),
                (
                    "clave",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cat_turnos",
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterField(
            model_name="departamento",
            name="clave",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="historicaldepartamento",
            name="clave",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpuesto",
            name="clave",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="puesto",
            name="clave",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="departamento",
            index=models.Index(fields=["nombre"], name="cat_departa_nombre_108e56_idx"),
        ),
        migrations.AddIndex(
            model_name="departamento",
            index=models.Index(fields=["activo"], name="cat_departa_activo_055f88_idx"),
        ),
        migrations.AddIndex(
            model_name="puesto",
            index=models.Index(fields=["nombre"], name="cat_puestos_nombre_0c7829_idx"),
        ),
        migrations.AddIndex(
            model_name="puesto",
            index=models.Index(
                fields=["departamento"], name="cat_puestos_departa_0da07f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="puesto",
            index=models.Index(fields=["activo"], name="cat_puestos_activo_e6735b_idx"),
        ),
        migrations.AddField(
            model_name="historicalhorario",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalturno",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="horario",
            index=models.Index(fields=["nombre"], name="cat_horario_nombre_d3b12b_idx"),
        ),
        migrations.AddIndex(
            model_name="horario",
            index=models.Index(fields=["activo"], name="cat_horario_activo_14b985_idx"),
        ),
        migrations.AddIndex(
            model_name="turno",
            index=models.Index(fields=["nombre"], name="cat_turnos_nombre_e1789f_idx"),
        ),
        migrations.AddIndex(
            model_name="turno",
            index=models.Index(fields=["activo"], name="cat_turnos_activo_6fe776_idx"),
        ),
    ]
