# Generated by Django 5.2.5 on 2025-08-24 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_empleado', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, default='', max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro/No especifica')], default='O', max_length=1)),
                ('estado_civil', models.CharField(choices=[('S', 'Soltero(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viudo(a)'), ('U', 'Unión libre')], default='S', max_length=1)),
                ('curp', models.CharField(max_length=18, unique=True, validators=[django.core.validators.MinLengthValidator(18), django.core.validators.RegexValidator('^[A-Z]{4}\\d{6}[HM][A-Z]{5}\\d{2}$', 'CURP inválida.')])),
                ('rfc', models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.RegexValidator('^[A-ZÑ&]{3,4}\\d{6}[A-Z0-9]{3}$', 'RFC inválido.')])),
                ('nss', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'NSS inválido (11 dígitos).')])),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('puesto', models.CharField(max_length=120)),
                ('departamento', models.CharField(max_length=120)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='empleados/fotos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'empleados',
                'indexes': [models.Index(fields=['num_empleado'], name='empleados_num_emp_e499d9_idx'), models.Index(fields=['apellido_paterno', 'apellido_materno', 'nombres'], name='empleados_apellid_4912be_idx'), models.Index(fields=['departamento'], name='empleados_departa_1b5399_idx'), models.Index(fields=['puesto'], name='empleados_puesto_db5e19_idx'), models.Index(fields=['activo'], name='empleados_activo_8ab26a_idx')],
            },
        ),
    ]
