# Generated by Django 5.2.5 on 2025-08-24 23:13

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogos", "0002_departamento_deleted_at_puesto_deleted_at_and_more"),
        (
            "empleados",
            "0002_rename_empleados_departa_1b5399_idx_empleados_departa_95a8c1_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="HistoricalEmpleado",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("num_empleado", models.CharField(db_index=True, max_length=20)),
                ("nombres", models.CharField(max_length=100)),
                ("apellido_paterno", models.CharField(max_length=100)),
                (
                    "apellido_materno",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                (
                    "genero",
                    models.CharField(
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Femenino"),
                            ("O", "Otro/No especifica"),
                        ],
                        default="O",
                        max_length=1,
                    ),
                ),
                (
                    "estado_civil",
                    models.CharField(
                        choices=[
                            ("S", "Soltero(a)"),
                            ("C", "Casado(a)"),
                            ("D", "Divorciado(a)"),
                            ("V", "Viudo(a)"),
                            ("U", "Unión libre"),
                        ],
                        default="S",
                        max_length=1,
                    ),
                ),
                (
                    "curp",
                    models.CharField(
                        db_index=True,
                        max_length=18,
                        validators=[
                            django.core.validators.MinLengthValidator(18),
                            django.core.validators.RegexValidator(
                                "^[A-Z]{4}\\d{6}[HM][A-Z]{5}\\d{2}$", "CURP inválida."
                            ),
                        ],
                    ),
                ),
                (
                    "rfc",
                    models.CharField(
                        db_index=True,
                        max_length=13,
                        validators=[
                            django.core.validators.MinLengthValidator(12),
                            django.core.validators.RegexValidator(
                                "^[A-ZÑ&]{3,4}\\d{6}[A-Z0-9]{3}$", "RFC inválido."
                            ),
                        ],
                    ),
                ),
                (
                    "nss",
                    models.CharField(
                        db_index=True,
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{11}$", "NSS inválido (11 dígitos)."
                            )
                        ],
                    ),
                ),
                ("telefono", models.CharField(blank=True, default="", max_length=20)),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("foto", models.TextField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogos.departamento",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "puesto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogos.puesto",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical empleado",
                "verbose_name_plural": "historical empleados",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
