# Generated by Django 5.2.5 on 2025-08-28 01:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0003_historicalhorario_historicalturno_horario_turno_and_more"),
        ("empleados", "0003_empleado_deleted_at_historicalempleado"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="banco",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="calle",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="celular",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="clabe",
            field=models.CharField(
                blank=True,
                max_length=18,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{18}$", "CLABE debe tener 18 dígitos."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="colonia",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="contacto_emergencia_nombre",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="contacto_emergencia_parentesco",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="contacto_emergencia_telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="cp",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="cuenta",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10,20}$", "Cuenta bancaria entre 10 y 20 dígitos."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="escolaridad",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="estado",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="horario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalogos.horario",
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="municipio",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="notas",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="numero",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="sueldo",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="tipo_contrato",
            field=models.CharField(
                blank=True,
                choices=[
                    ("determinado", "Determinado"),
                    ("indeterminado", "Indeterminado"),
                    ("obra", "Obra o proyecto"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="tipo_jornada",
            field=models.CharField(
                blank=True,
                choices=[
                    ("diurna", "Diurna"),
                    ("mixta", "Mixta"),
                    ("nocturna", "Nocturna"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="turno",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalogos.turno",
            ),
        ),
        migrations.AddField(
            model_name="historicalempleado",
            name="banco",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="historicalempleado",
            name="calle",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="historicalempleado",
            name="celular",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="historicalempleado",
            name="clabe",
            field=models.CharField(
                blank=True,
                max_length=18,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{18}$", "CLABE debe tener 18 dígitos."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="historicalempleado",
            name="colonia",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="historicalempleado",
            name="contacto_emergencia_nombre",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="historicalempleado",
            name="contacto_emergencia_parentesco",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="historicalempleado",
            name="contacto_emergencia_telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="historicalempleado",
            name="cp",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="historicalempleado",
            name="cuenta",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10,20}$", "Cuenta bancaria entre 10 y 20 dígitos."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="historicalempleado",
            name="escolaridad",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalempleado",
            name="estado",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="historicalempleado",
            name="horario",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="catalogos.horario",
            ),
        ),
        migrations.AddField(
            model_name="historicalempleado",
            name="municipio",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="historicalempleado",
            name="notas",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalempleado",
            name="numero",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="historicalempleado",
            name="sueldo",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalempleado",
            name="tipo_contrato",
            field=models.CharField(
                blank=True,
                choices=[
                    ("determinado", "Determinado"),
                    ("indeterminado", "Indeterminado"),
                    ("obra", "Obra o proyecto"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalempleado",
            name="tipo_jornada",
            field=models.CharField(
                blank=True,
                choices=[
                    ("diurna", "Diurna"),
                    ("mixta", "Mixta"),
                    ("nocturna", "Nocturna"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalempleado",
            name="turno",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="catalogos.turno",
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="apellido_materno",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="curp",
            field=models.CharField(
                blank=True,
                max_length=18,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(18),
                    django.core.validators.RegexValidator(
                        "^[A-Z]{4}\\d{6}[HM][A-Z]{5}\\d{2}$", "CURP inválida."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="departamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empleados",
                to="catalogos.departamento",
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="estado_civil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("soltero", "Soltero(a)"),
                    ("casado", "Casado(a)"),
                    ("union_libre", "Unión libre"),
                    ("divorciado", "Divorciado(a)"),
                    ("viudo", "Viudo(a)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="empleados/"),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="genero",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Masculino"),
                    ("F", "Femenino"),
                    ("O", "Otro/No especifica"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="nombres",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="nss",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{11}$", "NSS inválido (11 dígitos)."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="num_empleado",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="puesto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empleados",
                to="catalogos.puesto",
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="rfc",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(12),
                    django.core.validators.RegexValidator(
                        "^[A-ZÑ&]{3,4}\\d{6}[A-Z0-9]{3}$", "RFC inválido."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="historicalempleado",
            name="apellido_materno",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalempleado",
            name="curp",
            field=models.CharField(
                blank=True,
                max_length=18,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(18),
                    django.core.validators.RegexValidator(
                        "^[A-Z]{4}\\d{6}[HM][A-Z]{5}\\d{2}$", "CURP inválida."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalempleado",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="historicalempleado",
            name="estado_civil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("soltero", "Soltero(a)"),
                    ("casado", "Casado(a)"),
                    ("union_libre", "Unión libre"),
                    ("divorciado", "Divorciado(a)"),
                    ("viudo", "Viudo(a)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalempleado",
            name="genero",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Masculino"),
                    ("F", "Femenino"),
                    ("O", "Otro/No especifica"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalempleado",
            name="nombres",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="historicalempleado",
            name="nss",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{11}$", "NSS inválido (11 dígitos)."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalempleado",
            name="num_empleado",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="historicalempleado",
            name="rfc",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(12),
                    django.core.validators.RegexValidator(
                        "^[A-ZÑ&]{3,4}\\d{6}[A-Z0-9]{3}$", "RFC inválido."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalempleado",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name="empleado",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("num_empleado",),
                name="uq_empleado_num_vivo",
            ),
        ),
        migrations.AddConstraint(
            model_name="empleado",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("curp",),
                name="uq_empleado_curp_vivo",
            ),
        ),
        migrations.AddConstraint(
            model_name="empleado",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("rfc",),
                name="uq_empleado_rfc_vivo",
            ),
        ),
        migrations.AddConstraint(
            model_name="empleado",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("nss",),
                name="uq_empleado_nss_vivo",
            ),
        ),
    ]
