name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: rh_user
          POSTGRES_PASSWORD: rh_pass
          POSTGRES_DB: rh_db
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U rh_user -d rh_db"
          --health-interval=10s --health-timeout=5s --health-retries=5

    env:
      DJANGO_SECRET_KEY: dummy
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: 127.0.0.1,localhost
      DB_NAME: rh_db
      DB_USER: rh_user
      DB_PASSWORD: rh_pass
      DB_HOST: localhost
      DB_PORT: "5432"
      API_PAGE_SIZE: "10"
      JWT_ACCESS_MIN: "60"
      JWT_REFRESH_DAYS: "7"
      TZ: America/Mexico_City
      CORS_ALLOWED_ORIGINS: http://localhost:5173

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Django checks & migrate
        run: |
          python manage.py check
          python manage.py migrate --noinput

      - name: Linters
        run: |
          ruff check .
          ruff format --check .
          black --check .
          isort --check-only .

      - name: Tests
        run: |
          pytest -q
